#!/usr/bin/env python
# SConstruct

from estragon_build_godot import build_godot
from estragon_log import log
from os import path

root         = Dir('.').path
godot_dir    = path.join(root, 'godot')
target 	     = "release_debug"
godot_bin    = "godot-editor.bin"

def build_engine() :   
    try:
        builder = build_godot(godot_dir, True)
        target_arg    = "=".join(["target",target])
        builder.build_editor( " ".join([target_arg]))
        import os
        os.remove(godot_bin)
        import re
        regex = re.compile('*tools*')
        binary = None
        for droot, dirs, files in os.walk(godot_dir):
            for file in files:
                if regex.match(file):
                    binary = file

        # create symlink
        os.symlink(binary, godot_bin)
        import stat
        st = os.stat(godot_bin)
        os.chmod(godot_bin, st.st_mode | stat.S_IEXEC)
    except Exception:
        print ("an error occured, printing log : ")
        print(log.get_log())
        print("end of log \n")
        raise

build_engine()